[package]
name = "ocs-summary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.17", features = ["cargo"] }
git2 = "0.19.0"
log = "0.4.22"


ocs = { path = ".."}
